theme: jekyll-theme-minimal
title: homepage
description: i dont know how to do websites send help
 <!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<time></time>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}
</style>
</head>
<body>

<h1>My Website</h1>
<p>A website created by me.</p>

</body>
</html> 
